default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: wescoffay
  password:
  timeout: 5000

development:
  <<: *default
  database: wellnyss_development

test:
  <<: *default
  database: wellnyss_test

production:
  <<: *default
  database: wellnyss_production
