default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # AM: FYI I was unable to create the database because of the below username/password.
  # AM: If you're going to keep this, you should indicate in your project documentation that the user needs to use the proper username/password here.
  # username: wescoffay
  # password:
  timeout: 5000

development:
  <<: *default
  database: wellnyss_development

test:
  <<: *default
  database: wellnyss_test

production:
  <<: *default
  database: wellnyss_production
